// <auto-generated />
using System;
using JobListingsDatabaseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobListingsDatabaseService.Data.Migrations
{
    [DbContext(typeof(JobListingsDbContext))]
    [Migration("20230408104552_seperateUserFromAdvertisement")]
    partial class seperateUserFromAdvertisement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobListingsDatabaseService.Data.Advertisement", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Employer")
                        .HasColumnType("longtext");

                    b.Property<string>("EngagementType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipal")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Uuid");

                    b.ToTable("Advertisement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
