// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserPreferencesDatabaseService.Data;

#nullable disable

namespace UserPreferencesDatabaseService.Data.Migrations
{
    [DbContext(typeof(UserPreferencesDbContext))]
    [Migration("20230408112104_InitUserPreferences")]
    partial class InitUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobListingsDatabaseService.Data.InterestedAdvertisement", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("AdvertisementUuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserGuid");

                    b.ToTable("InterestedAdvertisement");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.UninterestedAdvertisement", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("AdvertisementUuid")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserGuid", "AdvertisementUuid");

                    b.ToTable("UninterestedAdvertisement");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.InterestedAdvertisement", b =>
                {
                    b.HasOne("JobListingsDatabaseService.Data.User", "User")
                        .WithMany("interestedAdvertisements")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.UninterestedAdvertisement", b =>
                {
                    b.HasOne("JobListingsDatabaseService.Data.User", "User")
                        .WithMany("uninterestedAdvertisements")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.User", b =>
                {
                    b.Navigation("interestedAdvertisements");

                    b.Navigation("uninterestedAdvertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
