// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserPreferencesDatabaseService.Data;

#nullable disable

namespace UserPreferencesDatabaseService.Data.Migrations
{
    [DbContext(typeof(UserPreferencesDbContext))]
    partial class UserPreferencesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobListingsDatabaseService.Data.InterestedAdvertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdvertisementUuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("interestedAdvertisements");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.UninterestedAdvertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdvertisementUuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UninterestedAdvertisement");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.InterestedAdvertisement", b =>
                {
                    b.HasOne("JobListingsDatabaseService.Data.User", "User")
                        .WithMany("interestedAdvertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.UninterestedAdvertisement", b =>
                {
                    b.HasOne("JobListingsDatabaseService.Data.User", "User")
                        .WithMany("UninterestedAdvertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobListingsDatabaseService.Data.User", b =>
                {
                    b.Navigation("UninterestedAdvertisements");

                    b.Navigation("interestedAdvertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
